### ISSUE TITLE
Handling multiple instances of objects (ie PlayerHealth, but multiple player's)

### ISSUE THREAD

**Issue by prodigga** [roboryantron/Unite2017#4]
Hey there, great talk..I'll be posting some questions and this is the first one.

A lot of your examples seem to fall apart when we start looking at "real world" examples where you would have multiple enemies, players, etc.

Let's look at your example with player prefab that has a Simple health component that reference the PlayerHealth asset. The UI would be wired up to look at this one health asset. What if I wanted to make a split screen game? Multiple player's? Seems like there would be a need to have to constantly instantiate new copies of these persistent scriptable assets so every player gets their own one. This would mean, if I wanted to display a health bar above players heads, I would have to (through code, at runtime), manually set the PlayerHealth reference on the Healthbar script to that players PlayerHealth variable.

player2Healthbar.SetHealthReference(player2Instance.PlayerHealth)

This goes against keeping everything modular but I can't see a way around it.

A better example might be enenies with Healthbar above their heads. They all need their own instance of EnemyHealth and all the Healthbars would need to be pointed at the correct EnemyHealth instance at runtime.

**Comment by myko** [comment]
Even if you instantiate the Health assets and assign the references at runtime it's still more modular and decoupled than before. This is because the HealthBar component is depending not on a player or an enemy component, but on a FloatVariable/Reference. This means that the HealthBar component is reusable in any other project as long as you have a FloatVariable to reference. HealthBar has no idea that it's the health of a player, enemy etc.

**Comment by andrueandersoncs** [comment]
@prodigga is correct, you do end up having to make instantiated copies if you intend to reuse any of the scriptable objects you make. This pattern works as a replacement for static classes but not as a means by which to create a game. 

While making a "model" or "data structure" for data you need to model DOES allow modularity, it is not significantly different than the model/view separation in MVC

**Comment by roboryantron** [comment]
Player Health as a variable is not always the best solution for all game types. For multiplayer, it can be used for a handle to local player's health for use in UI. If you have local multiplayer with a reasonably finite max players (like 4) it could still be useful to have it in a variable, with each player pointing to a different one and each health bar doing the same.

In the case of enemies, that just isn't a place where I would use this since there often is not a centralized feedback system for a single active enemy. There are cases where it makes sense to use on enemies, though. We just shipped a one-on-one vr fighting game where the enemy health was in a variable. You can also picture certain game types that have special HP meters for a boss.

Games often have plenty of candidates for a variable of this sort of global nature. Time spent in a level, quality settings options, analytics data, difficulty setting, etc. HP works out for some games and not for others.

What it comes down to is that this is another tool at your disposal to solve problems. It is still up to the user to be smart about how and when to use it.
