### ISSUE TITLE
Wouldn't source control be spammed with unnecessary changes caused by persistant scriptable assets being modified at run time?

### ISSUE THREAD

**Issue by prodigga** [roboryantron/Unite2017#6]
You mention briefly in the question section of your talk that there is code in your framework to revert these values to their original state. You mention that the PlayerHealth gets "reset to the default value on Start".  If you mean that the SimpleHealth script literally sets PlayerHealth.value = MaxHealth.value in Start, that means the PlayerHealth asset would remain modified when you stop running your game.

You would end up with potentially tens or hundreds of scriptable assets being modified (depending on the scale of your project), and you'd have to discard these changes every time in your source control before committing your work. That sounds like a nightmare!

Im really interested in this workflow, hence all the questions. Looking forward to your replies :)

**Comment by roboryantron** [comment]
This demo is a simplified version of what we use on real projects. The repo is what was used for the demo so I removed complexity in order to introduce a concept.

For the games that I have shipped with this, I have a Value to change at edit time and a non-serialized RuntimeValue that is used when the game is running. You can set RuntimeValue to value on first access or using a ISerializationCallbackReceiver.

Also, for our float variables in production I have the concept of min and max built int to each one.
