### ISSUE TITLE
Type mismatch in Demo05_Sets

### ISSUE THREAD

**Issue by RomanZhu** [roboryantron/Unite2017#8]
Hi! Great talk,  i wanted to push your ideas to our team, but found something dirty (type mismatch)
![fxbhfcgrrm_qgdhjapxnxa](https://user-images.githubusercontent.com/12017366/33420179-b2440a9a-d5be-11e7-90aa-22ea0a30a022.png)

Why is it happening? I just opened project and launched demo

I think the reason for that is referencing scene objects from asset, as it can't save them.
And if it would be actual type mismatch - i would get error when adding to the list :c

So is it fine? Can i ignore it and draw names of the scene obejcts in custom editor for that EnabledThings for example?

**Comment by Mixtrate** [comment]
I think this is due to the Scriptable object trying to reference a Gameobject, which would result in a type mismatch. I believe that the way Ryan implements this is a very clever way enable a reference to the gameobject.

For example in his [ThingDisabler Script](https://github.com/roboryantron/Unite2017/blob/master/Assets/Code/Sets/ThingDisabler.cs) (which is a Monobehaviour) he can do this:
```C#
Set.Items[i].gameObject.SetActive(false);
```
which allows his to reference the "Set" and find gameobjects then delete them.

Really clever, not sure if I'm answering this correctly however.

**Comment by Mixtrate** [comment]
Some more proof to the previous answer.
If we change [RuntimeSet ](https://github.com/roboryantron/Unite2017/blob/master/Assets/Code/Sets/RuntimeSet.cs)to:
```C#
public abstract class RuntimeSet<T> : ScriptableObject
{
	public List<string> gameobjectNames = new List<string>();
	public List<T> Items = new List<T>();

	public void Add(T thing, string name)
	{
		if (!Items.Contains(thing))
			Items.Add(thing);
			gameobjectNames.Add(name);
	}

	public void Remove(T thing, string name)
	{
		if (Items.Contains(thing))
			Items.Remove(thing);
			gameobjectNames.Remove(name);

	}
}
```

and change [Thing.cs](https://github.com/roboryantron/Unite2017/blob/master/Assets/Code/Sets/Thing.cs) to:
```C#
public class Thing : MonoBehaviour
{
	public ThingRuntimeSet RuntimeSet;

	private void OnEnable()
	{
		RuntimeSet.Add(this, this.name);
	}

	private void OnDisable()
	{
		RuntimeSet.Remove(this, this.name);
	}
}
```
we can see this is actually working.
![image 1](https://user-images.githubusercontent.com/3374247/33473400-8aaa8d72-d633-11e7-8430-f3bddf2e049a.png)


![](http://runeatrepeat.com/wp-content/uploads/2014/10/magic.gif)

**Comment by RomanZhu** [comment]
Yeah, i know it's working.
Assets can reference scene objects until new scene is loaded.

My question was: Can i ignore that "Type mismatch" labels  and be sure nothing will suddenly break

**Comment by roboryantron** [comment]
It is safe...

This is just an editor display issue, the data is in tact. What is happening is the inspector is assuming that it is resolving an asset reference rather than a scene object reference.

It is simple enough to make a custom editor for the inspector or to use a property drawer to get your display back for debugging. If you do not want to edit the data in the inspector, you can simply draw EditorGUI.ObjectField with allowSceneObjects true. If you do want it to be editable in the inspector it can get more complicated to do it genericly.
