### ISSUE TITLE
Event send an arg

### ISSUE THREAD

**Issue by Mixtrate** [roboryantron/Unite2017#9]
Hi, this system is exactly what I need.

Still learning how to use it.

Is there a way to send data with that event being raised? (e.g. send the gameobject or object name from which the event was raised)

**Comment by Mixtrate** [comment]
I'm trying to connect this question with #8. the set references a gameobject maybe? so can an event do this as well?

My understanding of this is not complete. 
![image](https://user-images.githubusercontent.com/3374247/33473041-0cd6c9de-d632-11e7-86e0-0f15e43734ef.png)

**Comment by IsaiahKelly** [comment]
Since `GameEvent` is just a ScriptableObject you could eaisly modify it and the `GameEventListener` and the `UnityEvent Response` to take an argument which contains the data you wish to pass along (GameObject, float, Vector3, etc.).

**Comment by roboryantron** [comment]
I am glad that people have reached the need for arguments, it is the natural next step! 

If you want to head down this path, you need a GameEvent<T> definition and then extend it with a GameObjectGameEvent : GameEvent<GameObject>. To leverage a listener with a Unity event, you will need to define new listener class and a Unity event that takes GameObject as well. I tend to end up with int, bool, and float events as well as other custom types.

The version of events that I built in the studio supports argument passing by way of generics and code generation to avoid boilerplate code definition. There is a dropdown to select the event type (it reflects all applicable types from the assembly) and will auto-gen classes if necessary. When dropping an event into a listener, it will automatically change the type of the listener to one that handles that event. I can not share the source for all of this, but the concepts are still valid.

**Comment by IsaiahKelly** [comment]
@roboryantron One small question: What's the actual difference between a GameEvent and a Variable in your production system? With your example code I quickly realized that I could just transplant the GameEvent listener code into a Variable to remove the need for an Update method to check for changes, but doesn't that mean I just changed the Variable into a GameEvent that now passes a parameter?

**Comment by roboryantron** [comment]
Nice catch! They kind of grew into each other over time. My current implementation has variable extending event, making them even more similar. and allowing for more code reuse including the code-gen stuff for new types.

I consulted with a lot of our designers concerning the idea of just making them the same thing. but everyone wanted the semantic split between event and variable.

**Comment by IsaiahKelly** [comment]
Interesting... Yeah, extending variable from event makes sense because you can think of an event as a kind of parameterless variable. Which is basically what I was going to make them in my own implementation. I have no problem with just calling them all variables, but I can see how a designer would prefer the separation.

I'd also just like to say that I find your designer friendly approach to things incredibility refreshing. It feels like so many programmers are really hostile towards the idea of giving designers any kind of power. I'm sure their views are somewhat justified, but it's really nice to find a programmer that has faith in the designer and wants to empower them. I can only guess this is because you've seen the war from both sides. 😉

Thanks for sharing all this knowledge with the community! Your latest Unit talk is probably the best one I've ever seen, and that's including the new job systems talk. 😁
